### ISSUE TITLE
Showing error when clicking register button

### ISSUE THREAD

**Issue by compressionmonkey** [keldenddorji1997/Passport_Authentication_System#2]
<img width="586" alt="Screen Shot 2019-08-04 at 10 06 27 PM" src="https://user-images.githubusercontent.com/17824272/62426254-3648be80-b704-11e9-87ff-8e9ed372d442.png">

Error: Could not find the include file "./partials/messages"
    at getIncludePath (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/ejs/lib/ejs.js:165:13)
    at includeSource (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/ejs/lib/ejs.js:309:17)
    at /Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/ejs/lib/ejs.js:719:26
    at Array.forEach (<anonymous>)
    at Template.generateSource (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/ejs/lib/ejs.js:695:15)
    at Template.compile (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/ejs/lib/ejs.js:572:12)
    at Object.compile (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/ejs/lib/ejs.js:392:16)
    at handleCache (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/ejs/lib/ejs.js:215:18)
    at tryHandleCache (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/ejs/lib/ejs.js:254:16)
    at View.exports.renderFile [as engine] (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/ejs/lib/ejs.js:485:10)

**Comment by compressionmonkey** [comment]
I just needed to remove <% include ./partials/messages %>
