### ISSUE TITLE
Shows up with this error while trying to click register

### ISSUE THREAD

**Issue by compressionmonkey** [keldenddorji1997/Passport_Authentication_System#3]
SyntaxError: Unexpected token ) in /Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/views/register.ejs while compiling ejs

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass async: true as an option.
    at new Function (<anonymous>)
    at Template.compile (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/ejs/lib/ejs.js:633:12)
    at Object.compile (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/ejs/lib/ejs.js:392:16)
    at handleCache (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/ejs/lib/ejs.js:215:18)
    at tryHandleCache (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/ejs/lib/ejs.js:254:16)
    at View.exports.renderFile [as engine] (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/ejs/lib/ejs.js:485:10)
    at View.render (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/express/lib/view.js:135:8)
    at tryRender (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/express/lib/application.js:640:10)
    at Function.render (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/express/lib/response.js:1012:7)
    at ServerResponse.res.render (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/express-ejs-layouts/lib/express-layouts.js:77:18)
    at router.get (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/routes/users.js:8:43)
    at Layer.handle [as handle_request] (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/express/lib/router/layer.js:95:5)
{ MongoNetworkError: failed to connect to server [clustertesting-shard-00-00-ucgrn.mongodb.net:27017] on first connect [MongoError: bad auth Authentication failed.]
    at Pool.<anonymous> (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/mongodb-core/lib/topologies/server.js:431:11)
    at Pool.emit (events.js:160:13)
    at connect (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/mongodb-core/lib/connection/pool.js:557:14)
    at callback (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/mongodb-core/lib/connection/connect.js:109:5)
    at provider.auth.err (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/mongodb-core/lib/connection/connect.js:352:21)
    at _authenticateSingleConnection (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/mongodb-core/lib/auth/auth_provider.js:66:11)
    at sendAuthCommand (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/mongodb-core/lib/auth/scram.js:215:18)
    at Connection.messageHandler (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/mongodb-core/lib/connection/connect.js:334:5)
    at Connection.emit (events.js:160:13)
    at processMessage (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/mongodb-core/lib/connection/connection.js:364:10)
    at TLSSocket.<anonymous> (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/mongodb-core/lib/connection/connection.js:533:15)
    at TLSSocket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at TLSSocket.Readable.push (_stream_readable.js:213:10)
    at TLSWrap.onread (net.js:599:20)
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {} }

**Comment by compressionmonkey** [comment]
More erros when specifying directory.
Error: Could not find the include file "&#39;./partials/messages&#39;"
    at getIncludePath (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/ejs/lib/ejs.js:165:13)
    at includeSource (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/ejs/lib/ejs.js:309:17)
    at /Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/ejs/lib/ejs.js:719:26
    at Array.forEach (<anonymous>)
    at Template.generateSource (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/ejs/lib/ejs.js:695:15)
    at Template.compile (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/ejs/lib/ejs.js:572:12)
    at Object.compile (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/ejs/lib/ejs.js:392:16)
    at handleCache (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/ejs/lib/ejs.js:215:18)
    at tryHandleCache (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/ejs/lib/ejs.js:254:16)
    at View.exports.renderFile [as engine] (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/ejs/lib/ejs.js:485:10)
    at View.render (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/express/lib/view.js:135:8)
    at tryRender (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/express/lib/application.js:640:10)
    at Function.render (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/express/lib/response.js:1012:7)
    at ServerResponse.res.render (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/node_modules/express-ejs-layouts/lib/express-layouts.js:77:18)
    at router.get (/Users/pc/Desktop/Passport_Authentication_System/Passport_Authentication_System/routes/users.js:8:43)
